### ISSUE TITLE
GET single namespace by prefix

### ISSUE THREAD

**Issue by javfg** [identifiers-org/cloud-hq-ws-registry#17]
Implement an API endpoint that, given a prefix, returns a single namespace.

**Comment by javfg** [comment]
Right now, you can ask for a single namespace appending a number as last parameter to the URL:

```/restApi/namespaces/4```

It might make more sense to switch that number (which is the index in the repository service, and makes no sense to the outside world) to a namespace prefix.

Might be better than adding a new endpoint.

**Comment by mbdebian** [comment]
I've added the capability of searching namespaces by prefix.
