### ISSUE TITLE
Add search in prefix registration request list

### ISSUE THREAD

**Issue by javfg** [identifiers-org/cloud-hq-ws-registry#36]

**Comment by mbdebian** [comment]
@javfg , was this for the curation dashboard?
Do you think we can close this issue?
Thanks!

**Comment by javfg** [comment]
It was left on the to-do list. Implementing a search filter on the PRR list to easily select requests, the same way it is working in the registry browser.

Up to you to close if it you think it is not worth it!

**Comment by renatocjn** [comment]
I'm closing this since we don't have enough requests to justify it.
